name: Release Electron App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. 检出完整仓库（包含 tags）
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. 安装 Node.js，并启用 npm 缓存
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # 根据项目需求调整
          cache: 'npm'

      # 3. 安装依赖
      - name: Install dependencies
        run: npm ci

      # 4. 项目构建（可自定义构建脚本）
      - name: Build project
        run: npm run build

      # 5. 使用 electron-builder 发布
      - name: Publish with electron-builder
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --publish always
