name: Release Electron App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npm ci

      - name: Ensure app-builder is executable
        run: chmod +x node_modules/app-builder-bin/linux/x64/app-builder

      - name: Build project
        run: npm run build

      - name: Publish with electron-builder
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx electron-builder --publish always
