name: Release Electron App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Update version in package.json
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}

          node <<EOF
          const fs = require('fs');
          const pkgPath = 'package.json';

          try {
            const pkg = JSON.parse(fs.readFileSync(pkgPath));
            console.log('Current version:', pkg.version);
            
            pkg.version = '$VERSION';
            fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));
            
            console.log('Updated version to:', '$VERSION');
          } catch (error) {
            console.error('Error updating package.json:', error);
            process.exit(1);
          }
          EOF

          echo "Updated package.json:"
          cat package.json | grep -A 1 '"version"'

      - name: Install dependencies
        run: |
          npm install
          npm ci

      - name: Ensure app-builder is executable
        run: chmod +x node_modules/app-builder-bin/linux/x64/app-builder

      - name: Set GH_TOKEN
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('GH_TOKEN', '${{ secrets.ACCESS_TOKEN }}')

      - name: Publish with electron-builder
        run: npm run release
